"""Image ingestion — load images from disk with validation.

INTEGRITY: Every metadata field returned is read from the actual file.
No invented coordinates, dimensions, or sensor names.
"""
from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

from app.core.exceptions import ImageLoadError


@dataclass
class ImageInfo:
    """Verified metadata about a loaded image."""
    path: str
    width: int
    height: int
    channels: int
    dtype: str
    file_size_bytes: int
    sha256: str          # content hash for cache keying
    is_synthetic: bool = False  # True if generated by make_synthetic_pair.py
    synthetic_label: str = ""   # e.g. "SYNTHETIC TEST DATA — reference"


def load_grayscale(path: str | Path, max_dimension: int = 4096) -> tuple[np.ndarray, ImageInfo]:
    """Load an image as grayscale uint8, with full validation.

    Supports: PNG, JPEG, TIFF, BMP, and any OpenCV-supported format.

    Args:
        path: Path to the image file.
        max_dimension: Reject images larger than this in either dimension.

    Returns:
        (image_array, ImageInfo) — grayscale uint8 array and metadata.

    Raises:
        ImageLoadError: If the file does not exist, cannot be decoded,
                        is corrupt, or exceeds max_dimension.
    """
    p = Path(path)

    if not p.exists():
        raise ImageLoadError(str(path), f"File not found: '{path}'.")
    if not p.is_file():
        raise ImageLoadError(str(path), f"Path is not a file: '{path}'.")

    file_size = p.stat().st_size
    if file_size == 0:
        raise ImageLoadError(str(path), "File is empty (0 bytes).")

    # SHA-256 for cache keying
    sha = hashlib.sha256(p.read_bytes()).hexdigest()

    # Load with OpenCV (handles most formats)
    img = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
    if img is None:
        # Fallback: try PIL
        try:
            pil = Image.open(p).convert("L")
            img = np.array(pil, dtype=np.uint8)
        except Exception as e:
            raise ImageLoadError(str(path), f"OpenCV and PIL both failed to decode: {e}") from e

    h, w = img.shape[:2]
    if h == 0 or w == 0:
        raise ImageLoadError(str(path), f"Decoded image has zero dimension: {w}×{h}.")

    if max(h, w) > max_dimension:
        raise ImageLoadError(
            str(path),
            f"Image dimension {w}×{h} exceeds maximum allowed {max_dimension}px. "
            "Use a cropped or downsampled version for this pipeline.",
        )

    info = ImageInfo(
        path=str(p),
        width=w,
        height=h,
        channels=1,
        dtype=str(img.dtype),
        file_size_bytes=file_size,
        sha256=sha,
    )
    return img, info


def load_color_as_gray(path: str | Path) -> tuple[np.ndarray, ImageInfo]:
    """Load a color image and convert to grayscale, returning both."""
    p = Path(path)
    if not p.exists():
        raise ImageLoadError(str(path), "File not found.")

    img_color = cv2.imread(str(p))
    if img_color is None:
        raise ImageLoadError(str(path), "Could not decode as color image.")

    img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
    h, w = img_gray.shape
    sha = hashlib.sha256(p.read_bytes()).hexdigest()

    info = ImageInfo(
        path=str(p),
        width=w,
        height=h,
        channels=img_color.shape[2] if img_color.ndim == 3 else 1,
        dtype=str(img_gray.dtype),
        file_size_bytes=p.stat().st_size,
        sha256=sha,
    )
    return img_gray, info
